name: fetch
description: Fetches files from the STEX

outputs:
  result:
    description: The result of a fetch operation on Simtropolis
  has-new-content:
    description: Whether new content was found and metadata was generated. If false, you can exit the action early.

runs:
  using: 'node20'
  main: 'fetch.js'
