name: Commit

on:
  workflow_dispatch: #

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_OWNER: sebamarynissen
      GITHUB_REPO: st-actions-test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - uses: actions/setup-node@v4
      - run: npm ci
      - uses: ./actions/commit
