name: Commit

on:
  workflow_dispatch: #

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      prs: ${{ steps.commit.outputs.prs }}
    env:
      GITHUB_OWNER: sebamarynissen
      GITHUB_REPO: st-actions-test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: Create & update PRs
        id: commit
        uses: ./actions/commit

  lint:
    needs: commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr: ${{ fromJson(needs.commit.outputs.prs) }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ matrix.pr.ref }}',
              state: 'pending',
              context: 'repository_dispatch',
              description: 'Currently linting',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.pr.ref }}
      - name: Run lint
        run: echo "Running linter"
