name: Lint

on:
  push:
    branches:
      - 'package/*'
  repository_dispatch:
    types: [lint]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_OWNER: sebamarynissen
      GITHUB_REPO: st-actions-test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: ${{ github.event.client_payload.sha }},
              state: 'success',
              context: 'repository_dispatch',
              description: 'Lint successful',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });
